version: 2.1
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    resource_class: small

    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true
          version: 20.10.12

      - run:
          name: Download and install docker compose
          command: |
            apk update && apk upgrade && apk add curl  
            curl -L "https://github.com/docker/compose/releases/download/v2.5.0/docker-compose-linux-x86_64" -o ~/docker-compose  
            chmod +x ~/docker-compose  
            mv ~/docker-compose /usr/local/bin/docker-compose


      - run:
          name: Spin up docker
          command: |
            docker-compose down -v   
            docker-compose up -d

      - deploy:
          name: Push application Docker image
          command: |
            docker login -e $DOCKER_HUB_EMAIL -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PWD
            docker tag cryptomock_circleci $DOCKER_HUB_USER_ID/cryptomock:$CIRCLE_SHA1
            docker tag cryptomock_circleci $DOCKER_HUB_USER_ID/cryptomock:latest
            docker push $DOCKER_HUB_USER_ID/cryptomock:$CIRCLE_SHA1
            docker push $DOCKER_HUB_USER_ID/cryptomock:latest
