version: 2.1
jobs:
  build:
    docker:
      - image: hwk613/cryptomock:0.0.1
        auth:
              username: hwk613
              password: $DOCKER_HUB_PWD
    
    steps:
      - checkout

      - setup_remote_docker:
          version: 20.10.14

      - run:
          name: Deploy Main to Firebase
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN

workflows:
  deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: main